config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get   '/help',       to: 'static_pages#help'

  get   '/about',      to: 'static_pages#about'

  get   '/contact',    to: 'static_pages#contact'

  get   '/for_point',  to: 'static_pages#for_point'
  get   '/for_device', to: 'static_pages#for_device'
  get   '/for_equip',  to: 'static_pages#for_equip'
  # get   '/for_gm',     to: 'static_pages#for_gm'

  get    '/signup',    to: 'users#new'
  post   '/signup',    to: 'users#create'

  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'


  resources :devices, only: [:index, :show, :create, :destroy, :edit, :update]
  resources :equips,  only: [:index, :edit,  :show, :update, :create, :destroy]
  resources :points,  only: [:index, :show,  :create, :destroy]
  resources :pgrades, only: [:edit,  :update]
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/point.rb
# == Schema Information
#
# Table name: points
#
#  id                  :integer          not null, primary key
#  original_thinckness :float
#  current_thinckness  :float
#  num                 :integer
#  equip_id            :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Point < ApplicationRecord
  belongs_to :equip
  default_scope -> { order(created_at: :desc) }

  validates :equip_id,            presence: true
  validates :original_thinckness, presence: true
  validates :current_thinckness,  presence: true
  validates :num,                 presence: true
  
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
    # require 'rubypython'
    before_action :logged_in_user, only: [:show, :create, :destroy, :index]
    before_action :real_user,      only: [:show, :create, :destroy, :index]
    def create
        @point = Point.new(point_params)
        if  @point.save
            flash[:success] = "Point created!"
            redirect_to request.referrer
        else
            flash[:danger] = "enter data don't blank"
            redirect_to request.referrer
        end
        begin
            Pgrade.new(point_num: @point.num, equip_id: @point.equip_id).save
        rescue ActiveRecord::RecordNotUnique
        end
    end

    def destroy
        @point = Point.find(params[:id])
        @point.destroy
        flash[:success] = "Point deleted"
        redirect_to request.referrer
    end

    def show 
        @minor_point  = 0
        @medium_point = 0
        @severe_point = 0
        b = []
        @point = Point.find(params[:id])
        @pgrade= Pgrade.find_by(point_num: @point.num ,equip_id: @point.equip_id )
        @equip = Equip.find(@point.equip_id) 
        @count = Point.where("num=?", @point.num).where("equip_id=?",@point.equip_id )
        @count.each do |msg|
            b.push(msg.current_thinckness)
            if (msg.current_thinckness)/(msg.original_thinckness) > @pgrade.minor_point and (msg.current_thinckness)/(msg.original_thinckness) <= 1
                @minor_point  += 1
            elsif  @pgrade.minor_point >= (msg.current_thinckness)/(msg.original_thinckness) and (msg.current_thinckness)/(msg.original_thinckness) > @pgrade.severe_point
                @medium_point += 1 
            else
                @severe_point += 1
            end
        end
        x = b.reverse
        n = current_user.gm_num
        @gm_result = 0
        RubyPython.start
        np = RubyPython.import("numpy")
        for_test = RubyPython.import("for_numpy")
        a=np.array(x)
        result = for_test.gm11(a,n).next()
        @gm_result = result
        print @gm_result
        # RubyPython.stop

    end

    def index
        #通过下面的方式指定了显示的内容为当前用户的数据
        @severe_list = []
        @medium_list = []
        @minor_list  = []
        @equip_ids = Equip.all().where(device_id:  current_user.devices.ids)
        @points    = Point.paginate(page: params[:page]).where(equip_id:  @equip_ids.ids)
        @points.each do |msg|
            @pgrade= Pgrade.find_by(point_num: msg.num ,equip_id: msg.equip_id )
            if (msg.current_thinckness)/(msg.original_thinckness) > @pgrade.minor_point and (msg.current_thinckness)/(msg.original_thinckness) <= 1
                @minor_list << msg.id
            elsif  @pgrade.minor_point >= (msg.current_thinckness)/(msg.original_thinckness) and (msg.current_thinckness)/(msg.original_thinckness) > @pgrade.severe_point
                @medium_list << msg.id
            else
                @severe_list << msg.id
            end
        end
    end

    private
        def point_params
            params.require(:point).permit(:num, :current_thinckness,
                                        :equip_id, :original_thinckness)
        end
end

app/helpers/points_helper.rb
module PointsHelper
    # def for_point
    #     point_xls = @points.to_xls.force_encoding("UTF-8")
    #     f = File.new( "points.xls", "w+")
    #     f.write(point_xls)
    #     f.close
    # end
    # <%= link_to "导出测点数据" , for_point_path %>
    # <button onclick="<% for_point %>" , class="btn-data">导出测点信息</button>
#     <script>
# function getSelectFile(){
# var fileName = document.getElementById("fileSelect").value;
# alert(fileName);
# }
# </script>
# <input id="fileSelect" type="file" />
# <input value="Get File" type="button" onclick="getSelectFile();" />

# require 'importex'  
# class Product < Importex::Base  
#   column "current_thinckness",:required => true  
#   column "equip_id", :type => Integer  
#   column "num", :type => Integer 
#   column "original_thinckness", :required => true
#   Product.import("points.xls")
#   Prodece = Product.all
#   Prodece.each do |p|
#     Point.create(equip_id: p["equip_id"],current_thinckness: p["current_thinckness"],num: p["num"],original_thinckness: p["original_thinckness"])
#   end
# end  

# file = "#{Rails.root}/tmp/preferred_offers.xlsx"

# xlsx       = Roo::Spreadsheet.open(file, extension: :xlsx)  

# file = "#{Rails.root}/tmp/points.xlsx"
# if File.exists?(file)    
#   xlsx   = Spreadsheet.open(file)
#   sheet  = xlsx.worksheet(0)  
#   sheet.each do |p|  
#     Point.create(equip_id: p[2],current_thinckness: p[1],num: p[4],original_thinckness: p[5])
#   end  
# end   



# class ImageUploader < CarrierWave::Uploader::Base

#     # Include RMagick or MiniMagick support:
#     # include CarrierWave::RMagick
#     # include CarrierWave::MiniMagick
  
#     # Choose what kind of storage to use for this uploader:
#     storage :file
#     # storage :fog
  
#     # Override the directory where uploaded files will be stored.
#     # This is a sensible default for uploaders that are meant to be mounted:
#     def store_dir
#       "/media/wind/工作/work/ruby_work/design/design/inputxls/#{model.id}"
#     end
  
#     # Provide a default URL as a default if there hasn't been a file uploaded:
#     # def default_url
#     #   # For Rails 3.1+ asset pipeline compatibility:
#     #   # ActionController::Base.helpers.asset_path("fallback/" + [version_name, "default.png"].compact.join('_'))
#     #
#     #   "/images/fallback/" + [version_name, "default.png"].compact.join('_')
#     # end
  
#     # Process files as they are uploaded:
#     # process scale: [200, 300]
#     #
#     # def scale(width, height)
#     #   # do something
#     # end
  
#     # Create different versions of your uploaded files:
#     # version :thumb do
#     #   process resize_to_fit: [50, 50]
#     # end
  
#     # Add a white list of extensions which are allowed to be uploaded.
#     # For images you might use something like this:
#     def extension_whitelist
#       %w(jpg jpeg gif png xls)
#     end
  
#     # Override the filename of the uploaded files:
#     # Avoid using model.id or version_name here, see uploader/store.rb for details.
#     def filename
#       if original_filename 
#         @name ||= Digest::MD5.hexdigest(File.dirname(current_path))
#         "#{@name}.#{file.extension}"
#       end
#     end
  
#   end
end

app/views/points/_point.html.erb
<li id="point-<%= point.id %>">
    <span class="device"><li><p><strong>当前设备</p><%= link_to point.equip.name, point.equip %></li></span>
    <span class="name"><li><p><strong>设备编号</p><%= point.equip.num %></li></span>
    <span class="name"><li><p><strong>测点编号</p><%= link_to point.num,  point_path(point.id)%></li></span>
    <span class="name"><li><p><strong>原始厚度</p><%= point.original_thinckness %></li></span>
    <span class="name"><li><p><strong>当前厚度</p><%= point.current_thinckness %></li></span>
    <span class="timestamp">
        发布于 <%= time_ago_in_words(point.created_at) %> 前.
        <% if current_user?(point.equip.device.user) %>
        <%= link_to "删除", point, method: :delete,
                                     data: { confirm: "确定?" } %>
        <% end  %>
    </span>
</li>
<br>
<br>

app/views/points/index.html.erb
<% provide(:title, '所有测点') %>
<%= link_to "导出测点数据" , for_point_path %>
<% provide(:button_text, '导入文件') %>
<div class="btn-data" style="width:150px;height:10px;border:none;outline:none;">
<%= form_for(current_user) do |f| %>
    <p><%= f.label "请输入导入的文件" %></p>
    <%= f.file_field :point_adrr ,style: "width:147px;height:10px;border:none;outline:none;"%> 
    <%= f.submit yield(:button_text), class: "btn btn-primary" ,style: "width:147px" %>
<% end %>
</div>

<h1>所有测点 (<%= @points.count %>)</h1>
<%= will_paginate %>
<div class="row">
    <aside class="col-md-4">
        <p><strong> 轻度腐蚀数 (<%= @minor_list.count %>)</p>
        <% @feed_point = Point.where(id: @minor_list )%>
            <% if @feed_point.any? %>
                <ol class="points">
                    <%= render @feed_point %>
                </ol>
            <% end %>
    </aside>

    <aside class="col-md-4">
        <p><strong> 中度腐蚀数 (<%= @medium_list.count %>)</p>
        <% @feed_point = Point.where(id: @medium_list)%>
            <% if @feed_point.any? %>
                <ol class="points">
                    <%= render @feed_point %>
                </ol>
            <% end %>
    </aside>

    <aside class="col-md-4">
        <p><strong> 严重腐蚀数 (<%= @severe_list.count %>)</p>
        <% @feed_point = Point.where(id: @severe_list)%>
            <% if @feed_point.any? %>
                <ol class="points">
                    <%= render @feed_point %>
                </ol>
            <% end %>

    </aside>
</div>
<%= will_paginate %>

app/views/points/show.html.erb
<% provide(:title, "测点") %>
<% provide(:button_text, '开始分析') %>
<% if current_user?(@point.equip.device.user) or current_user.admin? %>
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <p>
                    <li><h1><strong>当前设备名</h1><p><strong> <%= link_to @point.equip.name, @point.equip %></p></li>
                    <li><h1>当前设备编号</h1><p><strong> <%= @equip.num %></p></li>
                    <li><h1>当前测点编号</h1><p><strong> <%= link_to @point.num,  point_path(@point.id)%></p></li>
                    <li><h1>严重腐蚀阀值</h1><p><strong> <%= @pgrade.severe_point %></p></li>
                    <li><h1>轻度腐蚀阀值</h1><p><strong> <%= @pgrade.minor_point %></p></li>
                    <li><h1>测点原始长度</h1><p><strong> <%= @point.original_thinckness %></p></li>
                    <li><h1>测点本次长度</h1><p><strong> <%= @point.current_thinckness %></p></li>
                    <li><h1>测试次数</h1><p><strong>     <%= @count.count%></p></li>
                    <br>
                    <li>
                        <%= link_to "更新此腐蚀阀值",  edit_pgrade_path(@point)  %>
                    </li> 
                </p>
            </section>
        </aside>
        
        <aside class="col-md-4">
            <section class="user_info">
                <ol>
                <li><h1><strong>当前编号腐蚀程度表(/个)</h1></li>
                <%= column_chart ({"轻度" => @minor_point, "中度" => @medium_point, "严重" => @severe_point }) %>
                <br>
                </ol>
            </section>
            <br>
            <p>目前测试次数为  <%= @count.count%></p>
            <div style="width:150px;height:10px;border:none;outline:none;">
            <%= form_for(current_user) do |f| %>
                <p><%= f.label "请输入测点的第n次数" %></p>
                <%= f.text_field :gm_num ,style: "width:147px;height:10px;border:none;outline:none;"%> 
                <%= f.submit yield(:button_text), class: "btn btn-primary" ,style: "width:147px" %>
            <% end %>
            </div>
        </aside>
        <aside class="col-md-4">
        <section class="user_info">
                <ol>
                <li><h1><strong>当前编号腐蚀趋势图</h1></li>
                <%= line_chart @count.group(:created_at).minimum(:current_thinckness) %>
                <br>
                </ol>
            </section>
            <br>
            <p>经过系统分析后</p>
            <p>当前测点的厚度将变成：<%= @gm_result %></p>
        </aside>
    </div>
<% else %>
    <h1>不好意思，你不是当前用户</h1>
<% end %>