config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get   '/help',       to: 'static_pages#help'

  get   '/about',      to: 'static_pages#about'

  get   '/contact',    to: 'static_pages#contact'

  get   '/for_point',  to: 'static_pages#for_point'
  get   '/for_device', to: 'static_pages#for_device'
  get   '/for_equip',  to: 'static_pages#for_equip'
  # get   '/for_gm',     to: 'static_pages#for_gm'

  get    '/signup',    to: 'users#new'
  post   '/signup',    to: 'users#create'

  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'


  resources :devices, only: [:index, :show, :create, :destroy, :edit, :update]
  resources :equips,  only: [:index, :edit,  :show, :update, :create, :destroy]
  resources :points,  only: [:index, :show,  :create, :destroy]
  resources :pgrades, only: [:edit,  :update]
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id           :integer          not null, primary key
#  name         :string
#  introduction :text
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  num          :integer
#

class Device < ApplicationRecord
  has_many   :equips,       dependent: :destroy
  belongs_to :user
  validates  :user_id,      presence: true
  validates  :num,          presence: true
  validates  :name,         presence: true, length: { maximum: 20 }
  validates  :introduction, presence: true, length: { maximum: 140 }

  default_scope -> { order(created_at: :desc) }

  def feed_equip
    Equip.where("device_id = ?", id)
  end
    

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
    before_action :logged_in_user,   only: [:edit, :update, :index, :show, :create, :destroy]
    before_action :correct_device,   only: [:destroy, :edit, :update]

    def create
        begin
            @device = current_user.devices.build(device_params)
            @device.save
            flash[:success] = "Device created!"
            redirect_to root_url
        rescue ActiveRecord::RecordNotUnique 
            flash.now[:danger] = "Device has been exist!"
            @feed_items = []
            render 'static_pages/home'
        end
    end

    def edit
        @device = Device.find(params[:id])
    end

    def update
        @device = Device.find(params[:id])
        if @device.update_attributes(device_params)
          flash[:success] = "Device updated"
          redirect_to device_url(@device)
        else
          render 'edit'
        end
    end

    def show 
        @device = Device.find(params[:id])
        @equips = @device.equips.paginate(page: params[:page])
        if logged_in?
            @equip =  @device.equips.build
            @feed_equip_items = @device.feed_equip.paginate(page: params[:page])
        end
    end
    
    def destroy
        @device.destroy
        flash[:success] = "Device deleted"
        redirect_to request.referrer || root_url
    end

    def index
        @devices = current_user.devices.paginate(page: params[:page])
    end

    private
        def device_params
            params.require(:device).permit(:name,:introduction, :num)
        end

        def correct_device
            @device = current_user.devices.find_by(id: params[:id])
            redirect_to root_url if @device.nil?
        end

end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_device.html.erb
<li id="device-<%= device.id %>">
    <span class="user"><li><p><strong>当前用户</p><%= link_to device.user.name, device.user %></li></span>
    <span class="name"><li><p><strong>装置名</p><%= link_to device.name,      device_path(device.id)%></li></span>
    <span class="name"><li><p><strong>装置编号</p><%= device.num %></li></span>
    <span class="introduction"><li><p><strong>简介</p><%= device.introduction %></span>

    <span class="timestamp">
        发布于 <%= time_ago_in_words(device.created_at) %> 前.
        <% if current_user?(device.user) %>
        <%= link_to "删除", device, method: :delete,
                                      data: { confirm: "确定?" } %>
        <% end %>
    </span>
</li>
<br>
<br>

app/views/devices/_form.html.erb
<% if current_user?(@device.user) %>
	<%= form_for(@device) do |f| %>
	    <%= render 'shared/error_messages', object: f.object %>

	    <%= f.label "姓名" %>
	    <%= f.text_field :name, class: 'form-control' %>

	    <%= f.label "编号" %>
	    <%= f.text_field :num, class: 'form-control' %>

	    <%= f.label "简介" %>
	    <%= f.text_area :introduction, class: 'form-control' %>

	    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
	<% end %>
<% else %>
    <h1>不好意思，你不是当前用户</h1>
<% end %>

app/views/devices/edit.html.erb
<% provide(:title, "修改装置") %>
<% provide(:button_text, '保存修改') %>
<h1>更新你的装置</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/devices/index.html.erb
<% provide(:title, '所有装置') %>
<%= link_to "导出装置数据" , for_device_path %>
<% provide(:button_text, '导入文件') %>
<div class="btn-data" style="width:150px;height:10px;border:none;outline:none;">
<%= form_for(current_user) do |f| %>
    <p><%= f.label "请输入导入的文件" %></p>
    <%= f.file_field :device_adrr ,style: "width:147px;height:10px;border:none;outline:none;"%> 
    <%= f.submit yield(:button_text), class: "btn btn-primary" ,style: "width:147px" %>
<% end %>
</div>
<h1>所有装置 (<%= @devices.count %>)</h1>
<%= will_paginate %>

<ul class="devices">
    <%= render @devices %>
</ul> 

<%= will_paginate %>

app/views/devices/show.html.erb
<% provide(:title, @device.name) or current_user.admin? %>
<% if current_user?(@device.user) %>
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <p>
                    <li><h1><strong>当前装置</h1><p><strong><%= @device.name %></p></li>
                    <li><h1>编号</h1><p><strong><%= @device.num %></p></li>
                    <br>
                    <li><h1>装置的简介为</h1></li>
                    <li><p><strong><%= @device.introduction %></p></li>
                    <li>
                        <%= link_to "更新",  edit_device_path(@device)  %>
                    </li>
                </p>
            </section>
            <section class="equip_form">
                <%= render 'shared/equip_form' %>
            </section>

        </aside>
        <div class="col-md-8">
            <% if @device.equips.any? %>
                <h3>设备数 (<%= @device.equips.count %>)</h3>
                <ol class="equips">
                    <%= render 'shared/feed_equip' %>
                </ol>
            <% end %>
        </div>

    </div>

<% else %>
    <h1>不好意思，你不是当前用户</h1>
<% end %>