config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get   '/help',       to: 'static_pages#help'

  get   '/about',      to: 'static_pages#about'

  get   '/contact',    to: 'static_pages#contact'

  get   '/for_point',  to: 'static_pages#for_point'
  get   '/for_device', to: 'static_pages#for_device'
  get   '/for_equip',  to: 'static_pages#for_equip'
  # get   '/for_gm',     to: 'static_pages#for_gm'

  get    '/signup',    to: 'users#new'
  post   '/signup',    to: 'users#create'

  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'


  resources :devices, only: [:index, :show, :create, :destroy, :edit, :update]
  resources :equips,  only: [:index, :edit,  :show, :update, :create, :destroy]
  resources :points,  only: [:index, :show,  :create, :destroy]
  resources :pgrades, only: [:edit,  :update]
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/equip.rb
# == Schema Information
#
# Table name: equips
#
#  id            :integer          not null, primary key
#  specie        :string
#  name          :string
#  manufacturer  :string
#  material      :string
#  specification :string
#  device_id     :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  num           :integer
#

class Equip < ApplicationRecord
  has_many   :points,       dependent: :destroy
  has_many   :pgrades,      dependent: :destroy
  belongs_to :device
  default_scope -> { order(created_at: :desc) }

  validates  :device_id,        presence: true
  validates  :num,              presence: true
  validates  :specie,           presence: true, length: { maximum: 20 }
  validates  :name,             presence: true, length: { maximum: 20 }
  validates  :manufacturer,     presence: true, length: { maximum: 40 }
  validates  :material,         presence: true, length: { maximum: 20 }
  validates  :specification,    presence: true, length: { maximum: 40 }
  
  def feed_point
    Point.where("equip_id = ?", id)
  end
end

app/controllers/equips_controller.rb
class EquipsController < ApplicationController
    before_action :logged_in_user, only: [:edit, :update, :show, :create, :destroy, :index]
    before_action :real_user,      only: [:edit, :update, :show, :create, :destroy, :index]
    def create
        begin
            @equip = Equip.new(equip_params)
            @equip.save
            flash[:success] = "Equip created!"
            redirect_to request.referrer
        rescue ActiveRecord::RecordNotUnique 
            flash[:danger] = "Equip has been exist!"
            # @feed_equip_items = []
            redirect_to request.referrer
        end
    end

    def show 
        @equip = Equip.find(params[:id]) 
        @points = @equip.points.paginate(page: params[:page])    
        if logged_in?
            @point =  @equip.points.build
            @feed_point_items = @equip.feed_point.paginate(page: params[:page])
        end
    end

    def edit
        @equip = Equip.find(params[:id])
    end

    def update
        @equip = Equip.find(params[:id])
        if @equip.update_attributes(equip_edit_params)
          flash[:success] = "Equip updated"
          redirect_to equip_url(@equip)
        else
          render 'edit'
        end
    end

    def destroy
        @equip = Equip.find(params[:id])
        @equip.destroy
        flash[:success] = "Equip deleted"
        redirect_to request.referrer

    end

    def index
        @equips = Equip.paginate(page: params[:page]).where(device_id:  current_user.devices.ids)
    end

    private
        def equip_params
            params.require(:equip).permit(:specie, :name, :num, :device_id, :manufacturer,
                                          :material, :specification)
        end

        def equip_edit_params
            params.require(:equip).permit(:specie, :name, :num, :manufacturer,
                                          :material, :specification)
        end

end

app/helpers/equips_helper.rb
module EquipsHelper
end

app/views/equips/_equip.html.erb
<li id="equip-<%= equip.id %>">
    <span class="device"><li><p><strong>当前装置</p><%= link_to equip.device.name, equip.device %></li></span>
    <span class="name"><li><p><strong>设备种类</p><%= equip.specie %></li></span>
    <span class="name"><li><p><strong>设备名称</p><%= link_to equip.name,  equip_path(equip.id)%></li></span>
    <span class="name"><li><p><strong>设备编号</p><%= equip.num %></li></span>
    <span class="name"><li><p><strong>生产厂商</p><%= equip.manufacturer %></li></span>
    <span class="name"><li><p><strong>材质</p><%= equip.material %></li></span>
    <span class="name"><li><p><strong>规格</p><%= equip.specification %></li></span>
    <span class="timestamp">
        发布于 <%= time_ago_in_words(equip.created_at) %> 前.
        <% if current_user?(equip.device.user) %>
        <%= link_to "删除", equip, method: :delete,
                                     data: { confirm: "确定?" } %>
        <% end %>
    </span>
</li>
<br>
<br>

app/views/equips/_form.html.erb
<% if current_user?(@equip.device.user) or current_user.admin? %>    
    <%= form_for(@equip) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label "种类" %>
        <%= f.text_field :specie, class: 'form-control' %>
        
        <%= f.label "名称" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label "编号" %>
        <%= f.text_field :num, class: 'form-control' %>

        <%= f.label "生产厂商" %>
        <%= f.text_field :manufacturer, class: 'form-control' %>

        <%= f.label "材质" %>
        <%= f.text_field :material, class: 'form-control' %>

        <%= f.label "规格" %>
        <%= f.text_field :specification, class: 'form-control' %>

        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

<% else %>
    <h1>不好意思，你不是当前用户</h1>
<% end %>

app/views/equips/edit.html.erb
<% provide(:title, "编辑设备") %>
<% provide(:button_text, '保存修改') %>
<h1>更新你的设备</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/equips/index.html.erb
<% provide(:title, '所有设备') %>
<%= link_to "导出设备数据" , for_equip_path %>
<% provide(:button_text, '导入文件') %>
<div class="btn-data" style="width:150px;height:10px;border:none;outline:none;">
<%= form_for(current_user) do |f| %>
    <p><%= f.label "请输入导入的文件" %></p>
    <%= f.file_field :equip_adrr ,style: "width:147px;height:10px;border:none;outline:none;"%> 
    <%= f.submit yield(:button_text), class: "btn btn-primary" ,style: "width:147px" %>
<% end %>
</div>
<h1>所有设备 (<%= @equips.count %>)</h1>

<%= will_paginate %>

<ul class="equips">
	<%= render @equips %>
</ul> 

<%= will_paginate %>

app/views/equips/show.html.erb
<% provide(:title, @equip.name) %>
<% if current_user?(@equip.device.user) or current_user.admin? %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <p>
                <li><h1><strong>当前设备种类</h1><p><strong><%= @equip.specie %></p></li>
                <li><h1>当前设备名</h1><p><strong> <%= @equip.name %></p></li>
                <li><h1>编号</h1><p><strong> <%= @equip.num %></p></li>
                <li><h1>生产厂商</h1><p><strong><%= @equip.manufacturer %></p></li>
                <li><h1>材质</h1><p><strong><%= @equip.material %></p></li>
                <li><h1>规格</h1><p><strong><%= @equip.specification %></p></li>
            
                <li>
                    <%= link_to "更新",  edit_equip_path(@equip)  %>
                </li> 
            </p>
        </section>
    </aside>
    <aside class="col-md-4">
        <% if @equip.points.any? %>
            <h3>测点数 (<%= @equip.points.count %>)</h3>
            <ol class="points">
                <%= render @points %>
            </ol>
            <%= will_paginate @points %>
        <% end %>
    </aside>
    <aside class="col-md-4">
        <section class="point_form">
        <p>
            <li>
                <%= render 'shared/point_form' %>
            </li>
        </p>
        </section>
    </aside>
</div>

<% else %>
    <h1>不好意思，你不是当前用户</h1>
<% end %>