config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get   '/help',       to: 'static_pages#help'

  get   '/about',      to: 'static_pages#about'

  get   '/contact',    to: 'static_pages#contact'

  get   '/for_point',  to: 'static_pages#for_point'
  get   '/for_device', to: 'static_pages#for_device'
  get   '/for_equip',  to: 'static_pages#for_equip'
  # get   '/for_gm',     to: 'static_pages#for_gm'

  get    '/signup',    to: 'users#new'
  post   '/signup',    to: 'users#create'

  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'


  resources :devices, only: [:index, :show, :create, :destroy, :edit, :update]
  resources :equips,  only: [:index, :edit,  :show, :update, :create, :destroy]
  resources :points,  only: [:index, :show,  :create, :destroy]
  resources :pgrades, only: [:edit,  :update]
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
       <a href="http://127.0.0.1:3000/static_pages/home/">本系统</a>
        由 <a href="https://github.com/windkidtrh">谭锐华</a> 完成
    </small>
    <nav>
    <ul>
        <li><%= link_to "关于",   about_path  %></li>
        <li><%= link_to "联系我们", contact_path  %></li>
        <li><a href="http://news.railstutorial.org/">新闻</a></li>
    </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header  class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "石化腐蚀数据管理分析系统", root_path , id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "主页",   root_path  %></li>
                <li><%= link_to "帮助",   help_path  %></li>
                <% if logged_in? %>
                    <% if current_user.admin? %>
                        <li><%= link_to "用户", users_path %></li>
                    <% end %>
                    <li><%= link_to "装置",  devices_path  %></li>
                    <li><%= link_to "设备",   equips_path  %></li>
                    <li><%= link_to "测点",   points_path  %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            账户 <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "个人资料",  user_path(current_user)  %></li>
                            <li><%= link_to "设置", edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to "注销", logout_path, method: :delete %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "登录", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>